### ISSUE TITLE
orbital refund suggestion

### ISSUE THREAD

**Issue by AIFAFDcda** [jhowkNx/Master-Unlocker#11]
right now master unlocker for the orbital refund will set 1964179 to 2 and get 750k

But by writing these 2 globals  to max 1250000:
Global_262145.f_22854
Global_262145.f_22856
 
you will get 1.25mil for setting 1964179 to 2

**Comment by jhowkNx** [comment]
Thanks for sharing. I will look into this soon, it requires a bit of testing to verify that everything is okay.

**Comment by AIFAFDcda** [comment]
I have not tested since 1.58 that orbital refunds are even safe
