### ISSUE TITLE
Rockstar V-Neck T-Shirt?

### ISSUE THREAD

**Issue by PalastP** [jhowkNx/Master-Unlocker#13]
How can i get the **Rockstar V-Neck T-Shirt** with Master Unlocker unlock?

**Comment by jhowkNx** [comment]
Could using the option to unlock the Elite Challenge T-shirt give you this one as a bonus too? Unfortunately I can't see that right now.

**Comment by PalastP** [comment]
Unfortunately no, I unlocked everything with the Master Unlocker, only the Rockstar V-Neck T-Shirt is still missing.

**Comment by jhowkNx** [comment]
This item will be available in the next version, thanks for the feedback.
