### ISSUE TITLE
Missing Unlocks

### ISSUE THREAD

**Issue by AIFAFDcda** [jhowkNx/Master-Unlocker#17]
Missing Unlocks Globals:
Global_262145.f_7980 Bitch'n Dog Food T-shirt
Global_262145.f_7981 Vinyl Countdown T-shirt
Global_262145.f_7982 Homies Sharp T-shirt
Global_262145.f_14982 'Tennis' T-shirt

Wrong Stats:
{"AWD_DANCE_TO_SOLOMUN", 120},
{"AWD_DANCE_TO_TALEOFUS", 120},
{"AWD_DANCE_TO_DIXON", 120},
{"AWD_DANCE_TO_BLKMAD", 120},
SHOULD BE:
{"AWD_DANCE_TO_SOLOMUN", 360},
{"AWD_DANCE_TO_TALEOFUS", 360},
{"AWD_DANCE_TO_DIXON", 360},
{"AWD_DANCE_TO_BLKMAD", 360},

**Comment by jhowkNx** [comment]
Hello!
Thanks for sharing. I will test these and if I am not mistaken I had already added them, but I will review thoroughly.

**Comment by jhowkNx** [comment]
I checked and the globals you mentioned are outdated, But these are already in the current version of the Master Unlocker, Just go to > Unlock Exclusive Hats & Shirts.
And regarding stats, the values as much as 120 or 360 are functional, all checked on an account with new characters.
