### ISSUE TITLE
Want to get the original code

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [jhowkNx/Master-Unlocker#18]
I want to convert it to translate it into chinese and use it on other menus, but this script seems to be encrypted.
So i want to get the orginal code. i know some people are selling this script, but i will never sell it, it will be free forever.
But if you refuse to do so, you can close this issue. 😄
: )

**Comment by Galaxy-Studio-Code** [comment]
And my discord: @Blue-Flag:5246

**Comment by ham1tcagdas** [comment]
Dont share the code for safety. Chinese guys not trustable.

**Comment by Galaxy-Studio-Code** [comment]
If i just want to sell this, i will not create a issue here

**Comment by ham1tcagdas** [comment]
i m not the owner, i just dont want this codes to be exposed and patched by rockstar.

**Comment by Galaxy-Studio-Code** [comment]
But if you refuse to do so, you can close this issue. 😄

**Comment by Galaxy-Studio-Code** [comment]
yeah, we all use it,but this will not affect your use.I wont open it to the public

**Comment by jhowkNx** [comment]
Sorry, but currently I cannot leave this script without the 'encryption' which is actually nothing. You could easily read what is there, but I don't want to give details on how to do that.
