### ISSUE TITLE
Tip: Vehicle Warehouse

### ISSUE THREAD

**Issue by mgavdhout** [jhowkNx/Master-Unlocker#2]
Add function when move to new Vehicle Warehouse to fill the warehouse with 10 Standard, 10 Mid Range and 5 Top Range. That way you dont have to source 10 Standard + 10 Mid in order to always get as next car the Top Range.

**Comment by ham1tcagdas** [comment]
What is this, a new method?

**Comment by mgavdhout** [comment]
Hi, i just posted this as a Tip to improve.... Perhaps this is not the good
methode, sry i am new to GitHub...


Op wo 30 mrt. 2022 om 15:18 schreef ham1tcagdas ***@***.***>:

**Comment by jhowkNx** [comment]
I honestly don't think this is possible.

**Comment by mgavdhout** [comment]
Ok, thanks for the reply.

Op zo 3 apr. 2022 om 08:40 schreef jhowkNx ***@***.***>
