### ISSUE TITLE
More Collectibles:

### ISSUE THREAD

**Issue by ham1tcagdas** [jhowkNx/Master-Unlocker#21]
**Stunt Jumps:** There are 50 Stunt Jumps over Los Santos and Blaine County.

**Playing Cards:** There are 54 playing cards. (Collecting them all will reward the player with chips, RP, a unique High Roller Outfit, and an exclusive reward for Red Dead Online).

**Action Figures:** There are 100 action figures. (Collecting them all will reward the player a new hairstyle, an Impotent Rage outfit and GTA $50k).

**Peyote Plants:** (Seasonal only) There are 76 Peyote Plants.

**Signal Jammers:** There are 50 signal jammers to destroy. (Destroying them all will reward the player with GTA $50k, RP and unlocking Avi Schwartzman as a support heist crew.)

**Movie Props:** There are 10 Movie Props to collect for Solomon Richards.

**Hidden Caches:** 10 underwater packages to collect - reset daily.

**Treasure Chests:** 2 Treasure Chests can be collected on Cayo Perico daily.

**Shipwrecks:** 1 Shipwreck treasure chest in one of 30 possible locations can be collected daily. (Collecting 7 in a row rewards the player with "The Frontier" outfit.)

**Comment by jhowkNx** [comment]
All of these have been added except Peyote Plants, which activates but nothing happens in-game.
The others are doing well, but are undergoing improvements at the moment

**Comment by ham1tcagdas** [comment]
hi AGain this are missing in Contract mission unlock i can see only 1 is unlocked
![browser_BqNVv6GMcH](https://user-images.githubusercontent.com/101466850/177226019-0be99682-ba6a-40fb-838a-41b9011cd623.png)
![GTA5_vrzO99OJvr](https://user-images.githubusercontent.com/101466850/177226037-93adaeab-7100-4dae-9553-5c8988794268.jpg)
s

**Comment by ham1tcagdas** [comment]
And everything lose when i change session
![GTA5_UUfvYbcwzI](https://user-images.githubusercontent.com/101466850/177226093-657b9900-bebb-41fb-b02d-563208ed2131.jpg)
.
