### ISSUE TITLE
Missing 3 Arcade trophies

### ISSUE THREAD

**Issue by Una26** [jhowkNx/Master-Unlocker#3]
There are 3 missing Arcade trophies after using the "Unlock Arcade Trophys and Toys" feature. They are Gold Banana, Golden Arcade Machine and Master trophy. I would appreciate it if you could fix it. :)

Also, seems like the "NightClub Max Popularity" and "Unlock NightClub Awards" feature will mess up the night club total earning and warehouse sales complete number. Just to mention it to see if it's a bug or not.

**Comment by Una26** [comment]
I unload the menu, switch to a new session, but the Gold Banana and Master trophy are still not there. The Golden Arcade Machine does show up tho.

Did you mean increasing the popularity of the nightclub does not affect earnings, but the awards does?

**Comment by mgavdhout** [comment]
If you disable “Background Script” in the main 2Take1 Online Tap, and then go inside Arcade and you will see them. At least that worked for me. I think somehow this Script interfears.

Disable Background Script#

The background script is used by Rockstar to push code and perform live updates on the online game. Disabling this script will protect you from hot updates from Rockstar.

**Comment by Una26** [comment]
> If you disable “_Background Script_” in the main 2Take1 Online Tap, and then go inside Arcade and you will see them. At least that worked for me. I think somehow this _Background Script_ interfears.
> 
> _Disable Background Script#_
> 
> The background script is used by Rockstar to push code and perform live updates on the online game. Disabling this script will protect you from hot updates from Rockstar.

The Golden Arcade Machine did show up after I disable "Background Script", but the Golden banana and Master trophy are still missing. Anyway thank you for the information. :)

**Comment by Una26** [comment]
Update:

I created a new character and modified the level to 130. Then I bought an arcade in that save, completed the arcade setup mission and switched to a new session. After that I use the Arcade Unlockers feature and restart my game without any mod menu, but the Golden Banana and Master trophy are still not in the trophy case.

Hope that it will come to a solution soon. Thank you for this amazing script. :)

**Comment by jhowkNx** [comment]
Hello,
I will check out these trophies, and get back to you as soon as there is news.

**Comment by jhowkNx** [comment]
There was indeed a problem, but it has been identified and is already fixed in the next version.

**Comment by Una26** [comment]
> There was indeed a problem, but it has been identified and is already fixed in the next version.

Glad to hear that news! Look forward to the next version. :)

Also, would you consider to add a feature to unlock executive offices trophy and the agency office trophy in the future? (possibly include the MC clubhouse, bunker, auto shop, hangar if they have any trophies/toys to unlock)

**Comment by jhowkNx** [comment]
These features will be added over time, thanks for the feedback!
