### ISSUE TITLE
Re-arrange/categorize (more logic) the MENU

### ISSUE THREAD

**Issue by mgavdhout** [jhowkNx/Master-Unlocker#31]
Is it possible to re-arrange/categorize (more logic) the MENU (perhaps per DLC or Category e.g. Unlock, DLC's, Weapon etc.).

_Originally posted by @mgavdhout in https://github.com/jhowkNx/Master-Unlocker/discussions/30#discussioncomment-3331132_

**Comment by jhowkNx** [comment]
I will consider these improvements for future versions, thank you for the feedback.
