### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by ham1tcagdas** [jhowkNx/Master-Unlocker#35]
![image](https://user-images.githubusercontent.com/101466850/186140631-05141692-7a50-4ac1-8aea-a3805943cbca.png)
Causing crash that unlock only

**Comment by ham1tcagdas** [comment]
issue reason can be transaction pending error one of the unlocks causing.

**Comment by jhowkNx** [comment]
If you use the Unlock ALL option together with other options at the same time it can cause crashes. It is recommended to wait a bit (1 minute maybe) to use other unlock functions.

The transaction problem is something that 2Take1 is blocking and causing this, to stop receiving this error message it is recommended to restart the game once without the menu.

If you still experience crashes with different functions, I kindly ask you to clarify which function you used to crash your game.
