### ISSUE TITLE
Lua exception warning

### ISSUE THREAD

**Issue by mgavdhout** [jhowkNx/Master-Unlocker#5]
![image](https://user-images.githubusercontent.com/96773003/163562303-6f873f06-4f43-4f1f-9f70-d8330b3e536c.png)

**Comment by ham1tcagdas** [comment]
![GTA5_jKG7tOzayL](https://user-images.githubusercontent.com/101466850/163563742-158def0b-11a2-462a-8b39-4a68ac3123f2.jpg)

All i get now. its working

**Comment by jhowkNx** [comment]
Hello, this error message happens because I forgot to remove a leftover that was added from a previous build. 
Although, the error does not affect the feature itself.

**Comment by mgavdhout** [comment]
Hi, ok thanks for your message. I guess you will remove the leftover? Can you make that change into 1.18.1 ??

**Comment by jhowkNx** [comment]
Yes, this message has already been removed in the next version that will be available in the next few hours.
