### ISSUE TITLE
what was the message about low support donations?

### ISSUE THREAD

**Issue by ham1tcagdas** [jhowkNx/Master-Unlocker#55]
what was the message about low support donations?

**Comment by jhowkNx** [comment]
It means that future updates may not occur because there are other people benefiting (getting paid) using my work and script. While me, I get no support for the entire work.

**Comment by ham1tcagdas** [comment]
Make a code for activating it and Make it monthly 5usd Each time payment give us new code and we activate it on usage. Give us 28days activation code like that.

**Comment by jhowkNx** [comment]
I will still check what can be done, but I guarantee it won't be like this, anyway thanks for the support!
