### ISSUE TITLE
Casino Heist - Outfits Locked

### ISSUE THREAD

**Issue by ham1tcagdas** [jhowkNx/Master-Unlocker#6]
All of the Diamon Casino Heist - Outfits Locked.
Can you unlock them if possible? thanks.

![GTA5_DWdfSPQR1o](https://user-images.githubusercontent.com/101466850/163562662-aac5cca6-9f7a-42ca-9979-6edd8305c0dc.jpg)

**Comment by jhowkNx** [comment]
Using the unlock arcade options also unlocks the clothes from Casino Heist, have you tried it out?
