### ISSUE TITLE
Remove cooldown from Vehicle Cargo

### ISSUE THREAD

**Issue by mgavdhout** [jhowkNx/Master-Unlocker#7]
This does not work. What ever i try, i keep the timer (cooldown) after selling a Vehicle.

**Comment by jhowkNx** [comment]
Which job/vehicle have you tried that has this cooldown? Do you have a screenshot so I can check it out?

**Comment by mgavdhout** [comment]
I tested it again, and now it works... i can only think that i activated the options before i entered the vehicle warehouse, perhaps thats it....

**Comment by jhowkNx** [comment]
Thanks for reporting. May I will add a notification about it.
