### ISSUE TITLE
Recently donated, but only got an invalid Discord invite. 🙁

### ISSUE THREAD

**Issue by SlackerUnchained** [jhowkNx/Master-Unlocker#71]
Like the title line says. I recently donated with PayPal, but the resultant Discord link was invalid, so I couldn't actually get the Donor-version of the script. What should I do?

**Comment by dejectionn** [comment]
same, any luck with this?

**Comment by rosetannerc1** [comment]
Same here. Any luck?

**Comment by jhowkNx** [comment]
Hello, you guys can try to join using the discord link: https://discord.com/invite/KbXhCuwqdD
