### ISSUE TITLE
 mission selectors

### ISSUE THREAD

**Issue by WEFGH23** [jhowkNx/Master-Unlocker#75]
The bunker and air cargo mission selectors are not working, can you fix it?

**Comment by jhowkNx** [comment]
> The bunker and air cargo mission selectors are not working, can you fix it?

Hello. I will look into this issue. Thanks for reporting.

**Comment by lash7717** [comment]
How to get a sponsored edition?

**Comment by lash7717** [comment]
> > The bunker and air cargo mission selectors are not working, can you fix it?
> 
> Hello. I will look into this issue. Thanks for reporting.How to get a sponsored edition?
