### ISSUE TITLE
Increasing amount of agency jobs completed?

### ISSUE THREAD

**Issue by ham1tcagdas** [jhowkNx/Master-Unlocker#8]
are you able to adjust the amount of agency jobs completed?

Do we have this edit ?

**Comment by ham1tcagdas** [comment]
join date in Social Club can we change it ?

**Comment by jhowkNx** [comment]
The first comment may come in the next version of Heist Control.

The second, on the other hand, is totally impossible.

**Comment by ham1tcagdas** [comment]
> 

i just noticed LS Car Meet 1000 Level didnt work

**Comment by jhowkNx** [comment]
This option has been updated in the new version [1.21.0], please update and if there are any problems, open a new ticket and let me know!
