### ISSUE TITLE
No asset to download with Master Unlocker 1.21.0 release

### ISSUE THREAD

**Issue by bigfinfrank** [jhowkNx/Master-Unlocker#9]
[Master Unlocker 1.21.0](https://github.com/jhowkNx/Master-Unlocker/releases/tag/1.21.0) doesn't have a Master_Unlocker.zip file included in the assets and the source code zips are just the normal repo content as expected (so only `Donation.md` and `README.md`).

You should be able to [edit the release](https://github.com/jhowkNx/Master-Unlocker/releases/edit/1.21.0) and attach the Master_Unlocker.zip for version 1.21.0 without needing to create a new release. *Also while I have your attention it'd be nice to have the zip names include the version numbers, it's annoying to hit the replace button for every update when it's downloaded and again when unzipping (but this is a nitpick)*

**Comment by jhowkNx** [comment]
This was intentional. I had just added the changelog.
The file is now available for download, have fun.
